name: prepare-test-environment
description: "Checkout, select python version, install packages"

runs:
  using: "composite"
  steps:
  - uses: actions/checkout@v4
  - uses: actions/setup-python@v5
    with:
      python-version: '3.10' 
  - name: Install test packages
    shell: bash
    run: |
      pip install -r requirements.txt
      pip install -r test_requirements.txt
