AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Create a SQS and a lambda which reads from the queue and writes to RDS
Parameters:
  functionName:
    Description: The name of the lambda function
    Type: String
    MinLength: 1
    MaxLength: 30
  VPCsecurityGroupID:
    Description: The ID of the security group in the VPC
    Type: String
    MinLength: 1
    MaxLength: 300
  VPCsubnetIDlist:
    Description: A comma-separated list (in one string) of subnet IDs in the VPC
    Type: String
    MinLength: 1
    MaxLength: 300

Resources:

  queue:
    Type: AWS::SQS::Queue
    # Standard queue: all defaults are OK

  function:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:
        Ref: functionName
      Architectures:
        - x86_64
      MemorySize: 128
      PackageType: Zip
      Handler: lambda_function.lambda_handler
      Runtime: python3.10
      CodeUri: function
      Description: Read data from SQS and write to RDS
      Timeout: 10
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambda_ReadOnlyAccess
        - AWSLambdaVPCAccessExecutionRole
        - AWSLambdaSQSQueueExecutionRole
      Layers:
        - Ref: libs
      Events:
        SQSEvent:
          Type: SQS
          Description: Run the Lambda with an SQS event
          Properties:
            BatchSize: 1
            Enabled: true
            Queue: !GetAtt queue.Arn
      VpcConfig:
        SecurityGroupIds:
          - !Ref VPCsecurityGroupID
        SubnetIds: !Split [",", !Ref VPCsubnetIDlist]

  libs:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName:
        !Join
        - '-'
        - - !Ref functionName
          - 'layer'
      Description: Python packages used by the lambda.
      ContentUri: package
      CompatibleArchitectures:
        - x86_64
      CompatibleRuntimes:
        - python3.10
