name: bandit

on: [push]

jobs:
  bandit:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare test environment
        uses: ./.github/actions/prepare-test-environment
      - name: bandit
        run: python -m bandit -r . --exclude=/tests/,/venv/,/package/
