name: mypy

on: [push]

jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare test environment
        uses: ./.github/actions/prepare-test-environment
      - name: mypy
        run: python -m mypy . --exclude 'tests/' --exclude 'venv/' --exclude 'package/'
